### ISSUE TITLE
Validate bar failure in Bamboo

### ISSUE THREAD

**Issue by KuhuADT** [awasthan/ace-maven-plugin#3]
Hello Anand,

Thanks for the Plugin..!!
We are facing below error while running the my sample application in bamboo. In Bamboo plugin compilation is working fine but it seems to be during validation of bar file:

Below are the errors logs:

Failed to execute goal ibm.maven.plugins:ace-maven-plugin:11.29-SNAPSHOT:validate-bar-build-workspace (default-validate-bar-build-workspace) on project sample : **Error parsing .project file in: /home/bamboo/sample/target:** UnmarshalException: /home/bamboo/sample/target/.project (No such file or directory) ->
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ibm.maven.plugins:ace-maven-plugin:11.29-SNAPSHOT:validate-bar-build-workspace (default-validate-bar-build-workspace) on project FRS907: **Error parsing .project file in: /home/bamboo/sample/target**
build	27-Mar-2020 11:32:59	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
build	27-Mar-2020 11:32:59	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)

Could you please have a look into this and suggest.
Thanks in Advance.

**Comment by awasthan** [comment]
This is related to your project checkout location. I have added a troubleshooting section at the blog that addresses this.
